[package]
name = "snmpfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snmp = "0.2.2"
clap = { version = "3.1.18", features = ["derive"] }
